### ISSUE TITLE
Generating controller: SienaSupports - FATAL

### ISSUE THREAD

**Issue by missingcharacter** [lmcalpin/Play--Scaffold#8]
I've been having problems generating the views and controllers once it starts generating the SienaSupports Controller, here's the error:

executing command: scaffold:gen
17:46:01,379 INFO  ~ Starting C:\Users\Ricardo\workspace\Backhaul
17:46:01,383 INFO  ~ Module objectify is available (C:\play\modules\objectify-1.
0)
17:46:01,384 INFO  ~ Module scaffold is available (C:\play\modules\scaffold-head
)
17:46:01,385 INFO  ~ Module crudsiena is available (C:\play\modules\crudsiena-1.
5)
17:46:01,386 INFO  ~ Module siena is available (C:\play\modules\siena-1.5)
17:46:01,386 INFO  ~ Module gae is available (C:\play\modules\gae-1.4)
17:46:02,168 WARN  ~
17:46:02,169 WARN  ~ Google App Engine module
17:46:02,169 WARN  ~ ~~~~~~~~~~~~~~~~~~~~~~~
17:46:02,169 WARN  ~ No Google App Engine environment found. Setting up a develo
pment environement
17:46:02,187 WARN  ~ Don't forget to define your GAE application id in the 'war/
WEB-INF/appengine-web.xml' file
17:46:02,188 WARN  ~
17:46:02,188 WARN  ~ You're running Play! in DEV mode
17:46:04,842 INFO  ~ Generating controller: Users
17:46:04,844 INFO  ~ ! Skipping app/controllers/Users.java
17:46:04,845 INFO  ~ Generating views for Users
17:46:04,845 INFO  ~ ! Skipping app/views/Users/_form.html
17:46:04,846 INFO  ~ ! Skipping app/views/Users/create.html
17:46:04,847 INFO  ~ ! Skipping app/views/Users/show.html
17:46:04,847 INFO  ~ ! Skipping app/views/Users/edit.html
17:46:04,854 INFO  ~ ! Skipping app/views/Users/index.html
17:46:04,854 INFO  ~ Generating controller: SienaSupports
17:46:06,406 FATAL ~
java.lang.NullPointerException
        at play.templates.GroovyTemplate.cleanStackTrace(GroovyTemplate.java:253
)
        at play.templates.BaseTemplate.throwException(BaseTemplate.java:84)
        at play.templates.GroovyTemplate.render(GroovyTemplate.java:226)
        at play.modules.scaffold.generator.ScaffoldingGenerator.invokeTemplate(S
caffoldingGenerator.java:111)
        at play.modules.scaffold.generator.ScaffoldingGenerator.generate(Scaffol
dingGenerator.java:181)
        at play.modules.scaffold.generator.ScaffoldingGenerator.generateForEntit
y(ScaffoldingGenerator.java:216)
        at play.modules.scaffold.generator.ScaffoldingGenerator.generateControll
er(ScaffoldingGenerator.java:261)
        at play.modules.scaffold.generator.ScaffoldingGenerator.generate(Scaffol
dingGenerator.java:149)
        at play.modules.scaffold.generator.ScaffoldingGenerator.generate(Scaffol
dingGenerator.java:142)
        at play.modules.scaffold.Generate.generateScaffolding(Generate.java:179)

```
    at play.modules.scaffold.Generate.run(Generate.java:185)
    at play.modules.scaffold.Generate.main(Generate.java:197)
```

**Comment by missingcharacter** [comment]
By the way I have tried also disabling the CRUDSiena module and I get the same result.
